from enum import Enum


class L0Index(Enum):
    VOLUME_ID = 0
    PRODUCT_ID = 1
    PRODUCT_TYPE = 2
    FILE_SPECIFICATION_NAME = 3
    PRODUCT_CREATION_TIME = 4
    START_TIME = 5
    STOP_TIME = 6
    SPACECRAFT_CLOCK_START_COUNT = 7
    SPACECRAFT_CLOCK_STOP_COUNT = 8
    ORBIT_NUMBER = 9
    INSTRUMENT_MODE_ID = 10
    CH1_SWATH_WIDTH = 11
    CH1_SWATH_LENGTH = 12
    LINES = 13
    LINE_SAMPLES = 14
    BANDS = 15
    PDS_VERSION_ID = 16
    LABEL_REVISION_NOTE = 17
    DATA_SET_ID = 18
    RECORD_TYPE = 19
    MISSION_ID = 20
    MISSION_NAME = 21
    INSTRUMENT_HOST_ID = 22
    INSTRUMENT_HOST_NAME = 23
    INSTRUMENT_NAME = 24
    INSTRUMENT_ID = 25
    TARGET_NAME = 26
    TARGET_TYPE = 27
    MISSION_PHASE_NAME = 28
    PRODUCT_VERSION_TYPE = 29
    PRODUCER_INSTITUTION_NAME = 30
    SOFTWARE_NAME = 31
    SOFTWARE_VERSION_ID = 32
    L0_DESCRIPTION = 33
    DETECTOR_TEMPERATURE = 34
    SAMPLE_TYPE = 35
    SAMPLE_BITS = 36
    UNIT = 37
    BAND_STORAGE_TYPE = 38
    LINE_DISPLAY_DIRECTION = 39
    SAMPLE_DISPLAY_DIRECTION = 40
